AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-exam01-api

Globals:
  Function:
    Runtime: python3.9
    Architectures:
      - x86_64
    Timeout: 3
    Environment:
      Variables:
        API_TABLE: !Ref Exam01Table

Resources:
  Exam01Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
  CreateQuestionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: exam_api/
      Handler: create.lambda_handler
      Events:
        CreateQuestions:
          Type: Api
          Properties:
            Path: /exam01
            Method: POST
            RestApiId: !Ref ExamAPI
            #Auth:
            #  ApiKeyRequired: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Exam01Table
  SearchQuestionByIdFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: exam_api/
      Handler: searchById.lambda_handler
      Events:
        SearchByIdQuestions:
          Type: Api
          Properties:
            Path: /exam01/{id}
            Method: GET
            RestApiId: !Ref ExamAPI
            #Auth:
            #  ApiKeyRequired: true
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Exam01Table
  SearchQuestionByTextFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: exam_api/
      Handler: searchByText.lambda_handler
      Events:
        SearchByTextQuestions:
          Type: Api
          Properties:            
            Path: /exam01/search
            Method: POST
            RestApiId: !Ref ExamAPI
            #Auth:
            #  ApiKeyRequired: true
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Exam01Table
  SearchQuestionByTextV2Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: exam_api/
      Handler: searchByText_v2.lambda_handler
      Events:
        SearchByTextQuestions:
          Type: Api
          Properties:
            Path: /exam01/search/v2
            Method: POST
            RestApiId: !Ref ExamAPI
            #Auth:
            #  ApiKeyRequired: true
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Exam01Table
  ExamAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true # sets for all methods
Outputs:
  CreateQuestionAPI:
    Description: "API Gateway endpoint url for creating exam01 items"
    Value: !Sub "https://${ExamAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/exam01"
  CreateQuestionFunction:
    Description: "Create Question function ARN"
    Value: !GetAtt CreateQuestionFunction.Arn
  CreateQuestionFunctionIamRole:
    Description: "Create Question function IAM Role ARN"
    Value: !GetAtt CreateQuestionFunctionRole.Arn
  